services:
  - type: web
    name: coreinc   # Название твоего сервиса на Render
    runtime: image
    image:
      url: renderops/php:8.2-apache
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: core-db
          property: connectionString